from app.models import db, Tag, environment, SCHEMA
from sqlalchemy.sql import text

TAGS = [
    'Technology',
    'Science',
    'Education',
    'Entertainment',
    'Health & Wellness',
    'Travel',
    'Food & Cooking',
    'Sports',
    'Music',
    'Art & Design',
    'History',
    'Literature',
    'Fashion',
    'Beauty',
    'DIY & Crafts',
    'Gaming',
    'Movies & TV Shows',
    'News & Politics',
    'Business & Finance',
    'Personal Development',
    'Motivation & Inspiration',
    'Comedy',
    'Documentaries',
    'Nature & Wildlife',
    'Automotive',
    'Home Improvement',
    'Parenting',
    'Relationships',
    'Spirituality',
    'Fitness',
    'Yoga & Meditation',
    'Pets & Animals',
    'Gardening',
    'Photography',
    'Videography',
    'Technology Reviews',
    'Unboxing',
    'Tutorials',
    'Vlogs',
    'Podcasts',
    'Interviews',
    'Live Streams',
    'Short Films',
    'Animation',
    'Virtual Reality',
    'Augmented Reality',
    'Artificial Intelligence',
    'Machine Learning',
    'Blockchain',
    'Cryptocurrency',
    'Astronomy',
    'Physics',
    'Chemistry',
    'Biology',
    'Mathematics',
    'Engineering',
    'Architecture',
    'Psychology',
    'Sociology',
    'Anthropology',
    'Philosophy',
    'Religion',
    'Mythology',
    'Folklore',
    'Cultural Studies',
    'Language Learning',
    'Sign Language',
    'Public Speaking',
    'Writing & Publishing',
    'Book Reviews',
    'Poetry',
    'Theater',
    'Dance',
    'Magic & Illusions',
    'Stand-Up Comedy',
    'Sketch Comedy',
    'Parodies',
    'Pranks',
    'Challenges',
    'Social Experiments',
    'Charity & Fundraising',
    'Activism',
    'Environmental Issues',
    'Sustainable Living',
    'Minimalism',
    'Tiny Homes',
    'Van Life',
    'Off-Grid Living',
    'Survival Skills',
    'Camping & Hiking',
    'Fishing',
    'Hunting',
    'Extreme Sports',
    'Martial Arts',
    'Dance Fitness',
    'Pilates',
    'CrossFit',
    'Bodybuilding',
    'Nutrition',
    'Dieting',
    'Mental Health',
    'Self-Care',
    'Productivity',
    'Time Management',
    'Career Advice',
    'Job Interviews',
    'Resume Writing',
    'Freelancing',
    'Entrepreneurship',
    'Startups',
    'Investing',
    'Real Estate',
    'Stock Market',
    'Cryptocurrency Trading',
    'Personal Finance',
    'Budgeting',
    'Saving Money',
    'Debt Management',
    'Credit Scores',
    'Insurance',
    'Retirement Planning',
    'Estate Planning',
    'Legal Advice',
    'Consumer Rights',
    'Travel Vlogs',
    'Travel Guides',
    'Cultural Experiences',
    'Food Reviews',
    'Restaurant Reviews',
    'Cooking Tutorials',
    'Baking',
    'Grilling & BBQ',
    'Vegetarian & Vegan Recipes',
    'Gluten-Free Recipes',
    'Keto Recipes',
    'Paleo Recipes',
    'World Cuisine',
    'Street Food',
    'Food Challenges',
    'Wine & Spirits',
    'Coffee & Tea',
    'Home Brewing',
    'Cocktail Recipes',
    'Mixology',
    'Bartending',
    'Event Planning',
    'Party Ideas',
    'Wedding Planning',
    'Holiday Celebrations',
    'Seasonal Activities',
    'Luxury Travel',
    'Backpacking',
    'Road Trips',
    'Cruises',
    'Adventure Travel',
    'Eco-Tourism',
    'Travel Hacks',
    'Travel Safety',
    'Travel Photography',
    'Travel Gear Reviews',
    'Language & Culture',
    'Historical Sites',
    'Museums & Galleries',
    'Landmarks',
    'National Parks',
    'City Guides',
    'Rural Travel',
    'Island Getaways',
    'Beach Vacations',
    'Mountain Retreats',
    'Desert Adventures',
    'Winter Sports',
    'Skiing & Snowboarding',
    'Ice Skating',
    'Snowshoeing',
    'Sledding',
    'Winter Camping',
    'Hot Springs',
    'Wildlife Safaris',
    'Bird Watching',
    'Marine Life',
    'Scuba Diving',
    'Snorkeling',
    'Surfing',
    'Sailing',
    'Kayaking',
    'Canoeing',
    'Rafting',
    'Paddleboarding',
    'Jet Skiing',
    'Water Parks',
    'Amusement Parks',
    'Theme Parks',
    'Zoos & Aquariums',
    'Botanical Gardens',
    'Public Parks',
    'Urban Exploration',
    'Street Art',
    'Graffiti',
    'Murals',
    'Art Installations',
    'Art Exhibitions',
    'Art History',
    'Art Techniques',
    'Painting',
    'Drawing',
    'Sculpture',
    'Ceramics',
    'Pottery',
    'Glass Blowing',
    'Woodworking',
    'Metalworking',
    'Jewelry Making',
    'Textile Arts',
    'Weaving',
    'Knitting',
    'Crocheting',
    'Embroidery',
    'Quilting',
    'Sewing',
    'Fashion Design',
    'Costume Design',
    'Fashion Shows',
    'Fashion Trends',
    'Street Style',
    'Vintage Fashion',
    'Sustainable Fashion',
    'Fashion DIY',
    'Fashion Hauls',
    'Fashion Reviews',
    'Makeup Tutorials',
    'Skincare Routines',
    'Hair Care',
    'Hair Styling',
    'Nail Art',
    'Beauty Hacks',
    'Beauty Reviews',
    'Beauty Hauls',
    'Perfumes & Fragrances',
    'Spa & Wellness',
    'Massage Therapy',
    'Acupuncture',
    'Chiropractic Care',
    'Holistic Health',
    'Alternative Medicine',
    'Herbal Remedies',
    'Aromatherapy',
    'Essential Oils',
    'Natural Remedies',
    'Homeopathy',
    'Naturopathy',
    'Ayurveda',
    'Traditional Chinese Medicine',
    'Reiki',
    'Energy Healing',
    'Crystal Healing',
    'Sound Healing',
    'Meditation Techniques',
    'Mindfulness',
    'Breathwork',
    'Visualization',
    'Affirmations',
    'Gratitude Practices',
    'Journaling',
    'Creative Writing',
    'Storytelling',
    'Screenwriting',
    'Playwriting',
    'Scriptwriting',
    'Film Production',
    'Film Editing',
    'Cinematography',
    'Directing',
    'Acting',
    'Voice Acting',
    'Stunt Work',
    'Special Effects',
    'Makeup Effects',
    'Costume Design',
    'Set Design',
    'Prop Making',
    'Lighting Design',
    'Sound Design',
    'Music Production',
    'Music Composition',
    'Songwriting',
    'Music Theory',
    'Instrument Tutorials',
    'Vocal Training',
    'Choir Singing',
    'Band Performances',
    'Orchestra Performances',
    'Solo Performances',
    'Music Reviews',
    'Album Reviews',
    'Concert Reviews',
    'Music Festivals',
    'DJing',
    'Mixing & Mastering',
    'Music Technology',
    'Music History',
    'Music Genres',
    'Classical Music',
    'Jazz',
    'Blues',
    'Rock',
    'Pop',
    'Hip-Hop',
    'R&B',
    'Country',
    'Folk',
    'Reggae',
    'Latin Music',
    'World Music',
    'Electronic Music',
    'Dance Music',
    'Ambient Music',
    'Experimental Music',
    'Soundscapes',
    'Field Recordings',
    'Nature Sounds',
    'ASMR',
    'White Noise',
    'Binaural Beats',
    'Meditation Music',
    'Sleep Music',
    'Study Music',
    'Focus Music',
    'Relaxation Music',
    'Workout Music',
    'Running Music',
    'Yoga Music',
    'Dance Music',
    'Party Music',
    'Wedding Music',
    'Funeral Music',
    'Holiday Music',
    'Christmas Music',
    'Halloween Music',
    'Easter Music',
    'Thanksgiving Music',
    'Valentine’s Day Music',
    'Birthday Music',
    'Anniversary Music',
    'Graduation Music',
    'New Year’s Music',
    'Patriotic Music',
    'Religious Music',
    'Gospel Music',
    'Chanting',
    'Mantras',
    'Devotional Music',
    'Spiritual Music',
    'Sacred Music',
    'Meditative Music',
    'Healing Music',
    'Therapeutic Music',
    'Music Therapy',
    'Dance Therapy',
    'Art Therapy',
    'Drama Therapy',
    'Play Therapy',
    'Pet Therapy',
    'Equine Therapy',
    'Nature Therapy',
    'Forest Bathing',
    'Beach Therapy',
    'Mountain Therapy',
    'Desert Therapy',
    'Urban Therapy',
    'Adventure Therapy',
    'Wilderness Therapy',
    'Survival Therapy',
    'Sports Therapy',
    'Physical Therapy',
    'Occupational Therapy',
    'Speech Therapy',
    'Cognitive Therapy',
    'Behavioral Therapy',
    'Psychotherapy',
    'Counseling',
    'Life Coaching',
    'Career Coaching',
    'Executive Coaching',
    'Health Coaching',
    'Fitness Coaching',
    'Nutrition Coaching',
    'Wellness Coaching',
    'Relationship Coaching',
    'Parenting Coaching',
    'Financial Coaching',
    'Business Coaching',
    'Leadership Coaching',
    'Team Building',
    'Conflict Resolution',
    'Negotiation Skills',
    'Public Relations',
    'Marketing Strategies',
    'Social Media Marketing',
    'Content Marketing',
    'Email Marketing',
    'Affiliate Marketing',
    'Influencer Marketing',
    'Branding',
    'Logo Design',
    'Graphic Design',
    'Web Design',
    'UI/UX Design',
    'Product Design',
    'Interior Design',
    'Landscape Design',
    'Fashion Design',
    'Industrial Design',
    'Architectural Design',
    'Urban Planning',
    'Sustainable Design',
    'Green Building',
    'Eco-Friendly Products',
    'Recycling',
    'Upcycling',
    'Zero Waste',
    'Plastic-Free Living',
    'Composting',
    'Permaculture',
    'Organic Farming',
    'Hydroponics',
    'Aquaponics',
    'Vertical Farming',
    'Urban Gardening',
    'Community Gardens',
    'Farmers Markets',
    'Local Food',
    'Slow Food',
    'Food Security',
    'Food Justice',
    'Food Sovereignty',
    'Food Policy',
    'Food Safety',
    'Nutrition Education',
    'Healthy Eating',
    'Dietary Supplements',
    'Superfoods',
    'Herbal Medicine',
    'Functional Foods',
    'Nutritional Science',
    'Dietary Guidelines',
    'Food Allergies',
    'Food Intolerances',
    'Special Diets',
    'Weight Loss',
    'Weight Gain',
    'Body Positivity',
    'Eating Disorders',
    'Mindful Eating',
    'Intuitive Eating',
    'Culinary Arts',
    'Gastronomy',
    'Molecular Gastronomy',
    'Food Science',
    'Food Technology',
    'Food Innovation',
    'Food Trends',
    'Food Culture',
    'Food History',
    'Textbooks',
    'Lecture Notes',
    'Syllabi',
    'Course Outlines',
    'Study Guides',
    'Flashcards',
    'Practice Exams',
    'Past Exams',
    'Homework Assignments',
    'Lab Manuals',
    'Research Papers',
    'Case Studies',
    'Essays',
    'Dissertations',
    'Theses',
    'Project Reports',
    'Presentations',
    'Slideshows',
    'Video Lectures',
    'Podcasts',
    'Webinars',
    'Online Courses',
    'MOOCs (Massive Open Online Courses)',
    'E-books',
    'Journal Articles',
    'Conference Papers',
    'Technical Reports',
    'White Papers',
    'Datasets',
    'Software Tutorials',
    'Coding Exercises',
    'Problem Sets',
    'Mathematical Proofs',
    'Formulas & Equations',
    'Diagrams & Charts',
    'Graphs & Tables',
    'Infographics',
    'Mind Maps',
    'Concept Maps',
    'Annotated Bibliographies',
    'Literature Reviews',
    'Field Notes',
    'Lab Results',
    'Experiment Protocols',
    'Simulation Models',
    'Statistical Analyses',
    'Survey Results',
    'Questionnaires',
    'Interview Transcripts',
    'Focus Group Summaries',
    'Case Notes',
    'Clinical Guidelines',
    'Medical Records',
    'Patient Histories',
    'Treatment Plans',
    'Therapeutic Exercises',
    'Diagnostic Tests',
    'Radiology Images',
    'Pathology Reports',
    'Pharmacology References',
    'Anatomy Charts',
    'Physiology Diagrams',
    'Biochemistry Pathways',
    'Genetics Maps',
    'Microbiology Cultures',
    'Immunology Charts',
    'Epidemiology Data',
    'Public Health Reports',
    'Environmental Studies',
    'Geology Samples',
    'Geography Maps',
    'Meteorology Data',
    'Astronomy Charts',
    'Physics Equations',
    'Chemistry Reactions',
    'Biology Specimens',
    'Botany Samples',
    'Zoology Observations',
    'Ecology Reports',
    'Marine Biology Data',
    'Agricultural Studies',
    'Forestry Reports',
    'Wildlife Management',
    'Veterinary Science',
    'Nutrition Guides',
    'Dietary Plans',
    'Exercise Physiology',
    'Sports Science',
    'Kinesiology Studies',
    'Physical Therapy',
    'Occupational Therapy',
    'Speech Therapy',
    'Audiology Reports',
    'Nursing Care Plans',
    'Medical Ethics',
    'Health Policy',
    'Healthcare Management',
    'Business Plans',
    'Marketing Strategies',
    'Financial Analyses',
    'Accounting Ledgers',
    'Economic Models',
    'Management Theories',
    'Organizational Behavior',
    'Human Resources',
    'Operations Research',
    'Supply Chain Management',
    'Information Systems',
    'Data Science',
    'Machine Learning Algorithms',
    'Artificial Intelligence',
    'Computer Science',
    'Software Engineering',
    'Cybersecurity',
    'Network Architecture',
    'Database Management',
    'Web Development',
    'Mobile App Development',
    'Game Development',
    'User Experience Design',
    'Human-Computer Interaction',
    'Digital Media',
    'Graphic Design',
    'Animation',
    'Film Studies',
    'Photography',
    'Music Theory',
    'Music Composition',
    'Art History',
    'Visual Arts',
    'Performing Arts',
    'Theater Studies',
    'Dance Studies',
    'Literature Analysis',
    'Creative Writing',
    'Poetry',
    'Linguistics',
    'Language Learning',
    'Translation Studies',
    'Cultural Studies',
    'Anthropology',
    'Sociology',
    'Psychology',
    'Philosophy',
    'Political Science',
    'International Relations',
    'Law',
    'Criminology',
    'History',
    'Religious Studies',
    'Ethnography',
    'Urban Studies',
    'Rural Studies',
    'Gender Studies',
    'Queer Studies',
    'Disability Studies',
    'Postcolonial Studies',
    'Critical Race Theory',
    'Media Studies',
    'Communication Theory',
    'Journalism',
    'Public Relations',
    'Advertising',
    'Film Production',
    'Television Studies',
    'Radio Broadcasting',
    'Podcasting',
    'Digital Journalism',
    'Social Media Analysis',
    'Content Creation',
    'Influencer Marketing',
    'Brand Management',
    'Consumer Behavior',
    'Market Research',
    'Sales Strategies',
    'E-commerce',
    'Retail Management',
    'Hospitality Management',
    'Tourism Studies',
    'Event Management',
    'Sports Management',
    'Recreation Management',
    'Leisure Studies',
    'Culinary Arts',
    'Food Science',
    'Beverage Management',
    'Wine Studies',
    'Hospitality Law',
    'Hotel Management',
    'Restaurant Management',
    'Catering Management',
    'Food Safety',
    'Nutrition Science',
    'Dietetic Practice',
    'Clinical Nutrition',
    'Community Nutrition',
    'Sports Nutrition',
    'Public Health Nutrition',
    'Nutritional Epidemiology',
    'Food Policy',
    'Food Systems',
    'Agricultural Economics',
    'Agribusiness',
    'Sustainable Agriculture',
    'Agroecology',
    'Soil Science',
    'Crop Science',
    'Horticulture',
    'Animal Science',
    'Veterinary Medicine',
    'Animal Behavior',
    'Animal Welfare',
    'Wildlife Conservation',
    'Biodiversity',
    'Conservation Biology',
    'Environmental Science',
    'Environmental Policy',
    'Environmental Law',
    'Environmental Ethics',
    'Climate Science',
    'Climate Change',
    'Renewable Energy',
    'Energy Policy',
    'Sustainable Development',
    'Urban Planning',
    'Rural Development',
    'Community Development',
    'International Development',
    'Global Health',
    'Epidemiology',
    'Biostatistics',
    'Health Informatics',
    'Health Economics',
    'Health Policy',
    'Health Law',
    'Bioethics',
    'Medical Humanities',
    'Medical Anthropology',
    'Medical Sociology',
    'Health Communication',
    'Patient Education',
    'Health Promotion',
    'Disease Prevention',
    'Infectious Diseases',
    'Chronic Diseases',
    'Mental Health',
    'Substance Abuse',
    'Rehabilitation',
    'Geriatrics',
    'Pediatrics',
    'Obstetrics & Gynecology',
    'Oncology',
    'Cardiology',
    'Neurology',
    'Endocrinology',
    'Gastroenterology',
    'Hematology',
    'Immunology',
    'Nephrology',
    'Pulmonology',
    'Rheumatology',
    'Dermatology',
    'Ophthalmology',
    'Otolaryngology',
    'Orthopedics',
    'Plastic Surgery',
    'Emergency Medicine',
    'Critical Care',
    'Anesthesiology',
    'Radiology',
    'Pathology',
    'Surgery',
    'General Practice',
    'Family Medicine',
    'Internal Medicine',
    'Preventive Medicine',
    'Occupational Medicine',
    'Sports Medicine',
    'Travel Medicine',
    'Tropical Medicine',
    'Military Medicine',
    'Space Medicine',
    'Telemedicine',
    'Medical Technology',
    'Biomedical Engineering',
    'Biotechnology',
    'Genomics',
    'Proteomics',
    'Metabolomics',
    'Systems Biology',
    'Synthetic Biology',
    'Materials Science',
    'Chemical Engineering',
    'Civil Engineering',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Aerospace Engineering',
    'Marine Engineering',
    'Nuclear Engineering',
    'Acarology',
    'Actinology',
    'Aerobiology',
    'Agrobiology',
    'Algology',
    'Andrology',
    'Anthology',
    'Apiology',
    'Arachnology',
    'Astrobiology',
    'Astrology',
    'Audiology',
    'Autecology',
    'Bacteriology',
    'Bioecology',
    'Bryology',
    'Cetology',
    'Climatology',
    'Conchology',
    'Cosmology',
    'Cryology',
    'Cytology',
    'Dendrology',
    'Enology',
    'Entomology',
    'Ethnology',
    'Ethology',
    'Exobiology',
    'Felinology',
    'Florology',
    'Gastrology',
    'Gemology',
    'Gerontology',
    'Glaciology',
    'Gynecology',
    'Helminthology',
    'Hepatology',
    'Herpetology',
    'Histology',
    'Horology',
    'Hydrobiology',
    'Hydrology',
    'Ichthyology',
    'Kinesiology',
    'Lepidopterology',
    'Limnology',
    'Lithology',
    'Malacology',
    'Mammalogy',
    'Melittology',
    'Microbiology',
    'Mycology',
    'Myrmecology',
    'Nanotechnology',
    'Nephrology',
    'Nosology',
    'Odontology',
    'Ophthalmology',
    'Ornithology',
    'Osteology',
    'Otology',
    'Parasitology',
    'Penology',
    'Pharmacology',
    'Phycology',
    'Phytology',
    'Pomology',
    'Protozoology',
    'Pteridology',
    'Radiology',
    'Rheology',
    'Rhinology',
    'Selenology',
    'Seismology',
    'Serology',
    'Speleology',
    'Sphagnology',
    'Symbology',
    'Tectonophysics',
    'Teratology',
    'Toxicology',
    'Tribology',
    'Trichology',
    'Typology',
    'Urology',
    'Vexillology',
    'Volcanology',
    'Xylology'
]

# Adds a demo user, you can add other tags here if you want
def seed_tags():
    for tag in TAGS:
        db.session.add(Tag(name=tag))

    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the tags table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_tags():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.tags RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM tags"))

    db.session.commit()
